services:
  api-gateway:
    container_name: api-gateway
    build:
      context: ./api-gateway
      dockerfile: dockerfile
    ports:
      - "${API_GATEWAY_PORT}:${API_GATEWAY_PORT}"
    volumes:
    - ./api-gateway:/app
    - /app/node_modules  # prevent node_modules overwrite
    networks:
      - backend
    depends_on:
      - user-service
      - iot-service
      # - dataprocessing-service

  iot-service:
    container_name: iot-service
    build:
      context: ./iot-service
      dockerfile: dockerfile
    ports:
      - "${IOT_SERVICE_PORT}:${IOT_SERVICE_PORT}"
    volumes:
    - ./iot-service:/app
    - /app/node_modules  # prevent node_modules overwrite
    networks:
      - backend

  user-service:
    container_name: user-service
    build:
      context: ./user-service
      dockerfile: dockerfile
    ports:
      - "${USER_SERVICE_PORT}:${USER_SERVICE_PORT}"
    volumes:
    - ./user-service:/app
    - /app/node_modules  # prevent node_modules overwrite
    networks:
      - backend

  # dataprocessing-service:
  #   container_name: dataprocessing-service
  #   ports:
  #     - "${DATA_SERVICE_PORT}:${DATA_SERVICE_PORT}"
  #   networks:
  #     - backend

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./nginx-config/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api-gateway

  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"

  database:
    image: mongo
    container_name: database
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    volumes:
      - dbdata:/data/db

  kafka:
    image: confluentinc/cp-kafka:7.5.1
    container_name: kafka
    ports:
      - "${KAFKA_PORT}:${KAFKA_PORT}"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:${KAFKA_PORT},DOCKER://kafka:29092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:${KAFKA_PORT},DOCKER://0.0.0.0:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,DOCKER:PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:${ZOOKEEPER_PORT}
      KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - backend

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.1
    container_name: zookeeper
    ports:
      - "${ZOOKEEPER_PORT}:${ZOOKEEPER_PORT}"
    environment:
      ZOOKEEPER_CLIENT_PORT: ZOOKEEPER_PORT
      ZOOKEEPER_TICK_TIME: ${ZOOKEEPER_TICK_TIME}
    networks:
     - backend
  
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
      - "${AMQP_PORT}:${AMQP_PORT}"   # AMQP protocol port for your apps to connect
      - "${AMQP_UI_PORT}:${AMQP_UI_PORT}" # Management UI web interface
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    networks:
      - backend

volumes:
  dbdata:

networks:
  backend:
    driver: bridge